{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "undertow",
                    "vendor": "RedHat",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "all under 2.0.20"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in, all under 2.0.20, in the Undertow DEBUG log for io.undertow.request.security. If enabled, an attacker could abuse this flaw to obtain the user's credentials from the log files."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "vectorString": "4.8/CVSS:3.0/AV:N/AC:H/PR:H/UI:R/S:U/C:H/I:L/A:N",
                        "version": "3.0"
                    }
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-532",
                            "description": "CWE-532",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-12T00:00:00",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10212",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10212",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "RHSA-2019:2998",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2998",
                    "x_refsource": "REDHAT"
                },
                {
                    "name": "RHSA-2020:0727",
                    "url": "https://access.redhat.com/errata/RHSA-2020:0727",
                    "x_refsource": "REDHAT"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2019-10212",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "undertow",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "all under 2.0.20"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "RedHat"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw was found in, all under 2.0.20, in the Undertow DEBUG log for io.undertow.request.security. If enabled, an attacker could abuse this flaw to obtain the user's credentials from the log files."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "4.8/CVSS:3.0/AV:N/AC:H/PR:H/UI:R/S:U/C:H/I:L/A:N",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-532"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10212",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-10212"
                        },
                        {
                            "name": "RHSA-2019:2998",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2998"
                        },
                        {
                            "name": "RHSA-2020:0727",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2020:0727"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2019-10212",
        "dateUpdated": "2022-01-12T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "x_ValidationErrors": [
        "$ -- validator = oneOf"
    ]
}