{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "kernel",
                    "vendor": "[UNKNOWN]",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bounds write and a denial of service or unspecified other impact is possible by mounting and operating a crafted ext4 filesystem image."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "vectorString": "4.8/CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:H",
                        "version": "3.0"
                    }
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-787",
                            "description": "CWE-787",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "RHSA-2018:3083",
                    "url": "https://access.redhat.com/errata/RHSA-2018:3083"
                },
                {
                    "name": "USN-3753-2",
                    "url": "https://usn.ubuntu.com/3753-2/"
                },
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878"
                },
                {
                    "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee",
                    "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee"
                },
                {
                    "name": "USN-3871-5",
                    "url": "https://usn.ubuntu.com/3871-5/"
                },
                {
                    "name": "USN-3871-4",
                    "url": "https://usn.ubuntu.com/3871-4/"
                },
                {
                    "name": "[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package",
                    "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html"
                },
                {
                    "name": "RHSA-2018:2948",
                    "url": "https://access.redhat.com/errata/RHSA-2018:2948"
                },
                {
                    "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2",
                    "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2"
                },
                {
                    "name": "http://patchwork.ozlabs.org/patch/929238/",
                    "url": "http://patchwork.ozlabs.org/patch/929238/"
                },
                {
                    "name": "http://patchwork.ozlabs.org/patch/929237/",
                    "url": "http://patchwork.ozlabs.org/patch/929237/"
                },
                {
                    "name": "USN-3871-1",
                    "url": "https://usn.ubuntu.com/3871-1/"
                },
                {
                    "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199865",
                    "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199865"
                },
                {
                    "name": "RHSA-2018:3096",
                    "url": "https://access.redhat.com/errata/RHSA-2018:3096"
                },
                {
                    "name": "USN-3753-1",
                    "url": "https://usn.ubuntu.com/3753-1/"
                },
                {
                    "name": "USN-3871-3",
                    "url": "https://usn.ubuntu.com/3871-3/"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2018-10878",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "kernel",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "[UNKNOWN]"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw was found in the Linux kernel's ext4 filesystem. A local user can cause an out-of-bounds write and a denial of service or unspecified other impact is possible by mounting and operating a crafted ext4 filesystem image."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "4.8/CVSS:3.0/AV:P/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:H",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-787"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "RHSA-2018:3083",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2018:3083"
                        },
                        {
                            "name": "USN-3753-2",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3753-2/"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10878"
                        },
                        {
                            "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee",
                            "refsource": "CONFIRM",
                            "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=77260807d1170a8cf35dbb06e07461a655f67eee"
                        },
                        {
                            "name": "USN-3871-5",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3871-5/"
                        },
                        {
                            "name": "USN-3871-4",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3871-4/"
                        },
                        {
                            "name": "[debian-lts-announce] 20180718 [SECURITY] [DLA 1423-1] linux-4.9 new package",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2018/07/msg00020.html"
                        },
                        {
                            "name": "RHSA-2018:2948",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2018:2948"
                        },
                        {
                            "name": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2",
                            "refsource": "CONFIRM",
                            "url": "https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=819b23f1c501b17b9694325471789e6b5cc2d0d2"
                        },
                        {
                            "name": "http://patchwork.ozlabs.org/patch/929238/",
                            "refsource": "CONFIRM",
                            "url": "http://patchwork.ozlabs.org/patch/929238/"
                        },
                        {
                            "name": "http://patchwork.ozlabs.org/patch/929237/",
                            "refsource": "CONFIRM",
                            "url": "http://patchwork.ozlabs.org/patch/929237/"
                        },
                        {
                            "name": "USN-3871-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3871-1/"
                        },
                        {
                            "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199865",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.kernel.org/show_bug.cgi?id=199865"
                        },
                        {
                            "name": "RHSA-2018:3096",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2018:3096"
                        },
                        {
                            "name": "USN-3753-1",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3753-1/"
                        },
                        {
                            "name": "USN-3871-3",
                            "refsource": "UBUNTU",
                            "url": "https://usn.ubuntu.com/3871-3/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2018-10878",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}