{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "http://code.google.com/p/pyftpdlib/source/detail?r=344",
                    "url": "http://code.google.com/p/pyftpdlib/source/detail?r=344",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
                    "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py",
                    "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "http://code.google.com/p/pyftpdlib/issues/detail?id=71",
                    "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=71",
                    "x_refsource": "CONFIRM"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2008-7264",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The ftp_QUIT function in ftpserver.py in pyftpdlib before 0.5.0 allows remote authenticated users to cause a denial of service (file descriptor exhaustion and daemon outage) by sending a QUIT command during a disallowed data-transfer attempt."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "http://code.google.com/p/pyftpdlib/source/detail?r=344",
                            "refsource": "CONFIRM",
                            "url": "http://code.google.com/p/pyftpdlib/source/detail?r=344"
                        },
                        {
                            "name": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
                            "refsource": "CONFIRM",
                            "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
                        },
                        {
                            "name": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py",
                            "refsource": "CONFIRM",
                            "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn344&r=344&format=side&path=/trunk/pyftpdlib/ftpserver.py"
                        },
                        {
                            "name": "http://code.google.com/p/pyftpdlib/issues/detail?id=71",
                            "refsource": "CONFIRM",
                            "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=71"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2008-7264",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}