{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "kernel",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "before kernel 4.17-rc1",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw incorrect umask during file or directory modification in the Linux kernel NFS (network file system) functionality was found in the way user create and delete object using NFSv4.2 or newer if both simultaneously accessing the NFS by the other process that is not using new NFSv4.2. A user with access to the NFS could use this flaw to starve the resources causing denial of service."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-271",
                            "description": "CWE-271",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1911309",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1911309"
                },
                {
                    "name": "https://patchwork.kernel.org/project/linux-nfs/patch/20180403203916.GH20297@fieldses.org/",
                    "url": "https://patchwork.kernel.org/project/linux-nfs/patch/20180403203916.GH20297@fieldses.org/"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2020-35513",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "kernel",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "before kernel 4.17-rc1"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw incorrect umask during file or directory modification in the Linux kernel NFS (network file system) functionality was found in the way user create and delete object using NFSv4.2 or newer if both simultaneously accessing the NFS by the other process that is not using new NFSv4.2. A user with access to the NFS could use this flaw to starve the resources causing denial of service."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-271"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1911309",
                            "refsource": "MISC",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1911309"
                        },
                        {
                            "name": "https://patchwork.kernel.org/project/linux-nfs/patch/20180403203916.GH20297@fieldses.org/",
                            "refsource": "MISC",
                            "url": "https://patchwork.kernel.org/project/linux-nfs/patch/20180403203916.GH20297@fieldses.org/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2020-35513",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}