{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                    "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3"
                },
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802"
                },
                {
                    "name": "https://pypi.python.org/pypi/kerberos",
                    "url": "https://pypi.python.org/pypi/kerberos"
                },
                {
                    "name": "74760",
                    "url": "http://www.securityfocus.com/bid/74760"
                },
                {
                    "name": "https://github.com/apple/ccs-pykerberos/issues/31",
                    "url": "https://github.com/apple/ccs-pykerberos/issues/31"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2015-3206",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802"
                        },
                        {
                            "name": "https://pypi.python.org/pypi/kerberos",
                            "refsource": "CONFIRM",
                            "url": "https://pypi.python.org/pypi/kerberos"
                        },
                        {
                            "name": "74760",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/74760"
                        },
                        {
                            "name": "https://github.com/apple/ccs-pykerberos/issues/31",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/apple/ccs-pykerberos/issues/31"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2015-3206",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}